Feature/handler size gg23 gg24
Datenworks/ggenerator pull request #28
Opened 2020-03-03 13:24 UTC by tadeuif

Size ausente e size inválido

2020-03-03 14:08 UTC, lucasfernando commented on main.py
> +run()
Why is this line here?

2020-03-03 14:18 UTC, lucasfernando requested changes
There are a fews things to fix and please remove fake_generator_sample1

2020-03-03 14:18 UTC, lucasfernando commented on src/generators/handler.py
> +            raise ValueError("Não possui datasets")
All the messages by default are in English

2020-03-03 14:18 UTC, lucasfernando commented on src/generators/handler.py
> +                raise ValueError("Propriedade ‘size’ deve ser maior que 0 (zero)")
English

2020-03-03 14:18 UTC, lucasfernando commented on src/generators/handler.py
> +                '''raise ValueError("Dataset XPTO: Propriedade ‘size’ é obrigatória")''' #levantando a exceção de arquivo mal formado no validator.py
I think this line is unnecessary

2020-03-03 14:18 UTC, lucasfernando commented on src/lib/config/validator.py
> +            raise ValueError("Arquivo mal formado/campo vazio")
English

2020-03-03 14:18 UTC, lucasfernando commented on src/lib/config/validator.py
> +        try:
What do you think about use try catch just around the `json.loads`

2020-03-05 15:19 UTC, tadeuif commented
Guys, now when we have the size error, the program will raise a more friendly message. Other changes are done with the #35 PR. Can you pls review it?
Tks!

2020-03-05 17:22 UTC, lucasfernando approved these changes
We can do some improvements, but I think this should work for now.

2020-03-05 17:23 UTC, merged